persistent_worker:
  isolation:
    container:
      image: debian:latest
      cpu: 16
      memory: 64GB
      volumes:
        - /path/on/host:/path/in/container
        - /tmp/persistent-cache:/tmp/cache:ro

task:
  - df -h
